services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # This maps the .env value to the Docker build process
        - API_URL=${API_URL}
        - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    image: next-gin:latest
    container_name: next-gin-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always